In [1]:
# Experiment no : 05

In [2]:
# Aim :Creating dimensional array

In [3]:
# Name : Shreya Thakare
# Roll no : 64
# Section : C
# Subject : ET1

In [1]:
import numpy as np

In [10]:
#creating 1D array
a1=np.array([10,20,30,40,])

In [11]:
a1

array([10, 20, 30, 40])

In [13]:
#creating2D array
a2=np.array([[11,30,20,40],[34,89,47,34]])

In [14]:
a2

array([[11, 30, 20, 40],
       [34, 89, 47, 34]])

In [15]:
#creating 3D array
a3=np.matrix('11,23;33,45;67,78')

In [16]:
a3

matrix([[11, 23],
        [33, 45],
        [67, 78]])

In [17]:
#create array of 25 random integers between 20 and 23(inclusive)
arr=np.random.randint(20,24,size=25)
print(arr)

[21 23 23 22 22 20 21 22 23 22 23 20 21 21 22 21 20 22 22 23 22 20 23 23
 21]
